// Copyright (C) 2005-2007 - John Burkardt
// Copyright (C) 2009-2010 - Digiteo - Michael Baudin
//
// This file must be used under the terms of the GNU Lesser General Public License license
// http://www.gnu.org/copyleft/lesser.html

#ifndef _LOWDISC_HALTON_D_H_
#define _LOWDISC_HALTON_D_H_

#ifdef _MSC_VER
	#if LIBLOWDISC_EXPORTS 
		#define LOWDISC_IMPORTEXPORT __declspec (dllexport)
	#else
		#define LOWDISC_IMPORTEXPORT __declspec (dllimport)
	#endif
#else
	#define LOWDISC_IMPORTEXPORT
#endif

#undef __BEGIN_DECLS
#undef __END_DECLS
#ifdef __cplusplus
# define __BEGIN_DECLS extern "C" {
# define __END_DECLS }
#else
# define __BEGIN_DECLS /* empty */
# define __END_DECLS /* empty */
#endif

__BEGIN_DECLS

// The scrambling methods
// No scrambling
static int halton_scramblingZero = 1;
// Kocis - Whiten scrambling
static int halton_scramblingRR2 = 2;


// halton_start --
// startup the sequence.
//	
//  Parameters:
//
//    * dim_num, the spatial dimension, 
//      Default: dim_num = 1;
//      Required: 1 <= dim_num is required.
//
//    * seed[0,1,...,dim_num-1], the Halton sequence element corresponding to index = 0.
//      Default seed = (0, 0, ... 0).  
//      Required: 0 <= seed[0,1,...,dim_num-1].
//
//    * leap[0,1,...,dim_num-1], the succesive jumps in the Halton sequence.
//      Default: leap = (1, 1, ..., 1). 
//      Required: 1 <= leap[0,1,...,dim_num-1].
//
//    * base[0,1,...,dim_num-1], the Halton bases.
//      Default: base = (2, 3, 5, 7, 11, ... ). 
//      If base[i] = 0 then the prime number #i is automatically set.
//	    If base[i] > 1 then the base is directly used.
//	    If base[i] <0 or base[i] = 1, this is an error.
//
//    * scrambling, the scrambling method
//      halton_scramblingZero (i.e. no scrambling) or halton_scramblingRR2
//
void halton_start ( int dim_num , int base[] , int seed[] , int leap[] , int scrambling);

// halton_stop --
// shutdown the sequence.
//
// Description
//  Deletes the unnecessary memory.
void halton_stop ( );

// halton_next --
//   Computes the next element in a leaped Halton subsequence.
//
// Parameters
//
//    * index, the subsequence index.
//      Default: index = 0.
//      Required: 0 <= index.
//
//    * Output, double r[0,1,...,dim_num-1], the next element of the leaped Halton
//    subsequence.
//
//  Discussion:
//
//    The dim_num-dimensional Halton sequence is really dim_num separate
//    sequences, each generated by a particular base.
//
//    This routine selects elements of a "leaped" subsequence of the 
//    Halton sequence.  The subsequence elements are indexed by a
//    quantity called index, which starts at 0.  The index-th subsequence 
//    element is simply element 
//
//      seed[0,1,...,dim_num-1] + index * leap[0,1,...,dim_num-1]
//
//    of the original Halton sequence.
//
//    Call halton_start() before calling halton_next.
// Example
//  With dim_num=3, leap[i]=1 (for i=1,2,3), base=[2,3,5].
//  No scrambling.
//  0:   0.        0.           0.   
//  1:   0.5       0.3333333    0.2   
//  2:   0.25      0.6666667    0.4   
//  3:   0.75      0.1111111    0.6   
//  4:   0.125     0.4444444    0.8   
//  5:   0.625     0.7777778    0.04  
//  6:   0.375     0.2222222    0.24  
//  7:   0.875     0.5555556    0.44  
//  8:   0.0625    0.8888889    0.64  
//  9:   0.5625    0.0370370    0.84  
// 10:   0.3125    0.3703704    0.08  
//
// Example:
//  With dim_num=3, leap[i]=1 (for i=1,2,3), base=[2,3,5].
//  RR2 scrambling.
//  0:   0.        0.           0.   
//  1:   0.5       0.6666667    0.8   
//  2:   0.25      0.3333333    0.4   
//  3:   0.75      0.2222222    0.2   
//  4:   0.125     0.8888889    0.6   
//  5:   0.625     0.5555556    0.16  
//  6:   0.375     0.1111111    0.96  
//  7:   0.875     0.7777778    0.56  
//  8:   0.0625    0.4444444    0.36  
//  9:   0.5625    0.0740741    0.76  
// 10:   0.3125    0.7407407    0.08
void halton_next ( int index , double r[] );

// halton_dim_num_get 
// gets the spatial dimension for a leaped Halton subsequence.
int halton_dim_num_get ( void );

// halton_base_get 
// gets the base vector for a leaped Halton subsequence.
void halton_base_get ( int base[] );

// halton_leap_get 
// gets the leap vector for a leaped Halton subsequence.
void halton_leap_get ( int leap[] );

// halton_seed_get 
// gets the seed vector for a leaped Halton subsequence.
void halton_seed_get ( int seed[] );

// halton_step_get 
// gets the step for the leaped Halton subsequence.
int halton_step_get ( void );

//  halton_isstart --
//     Returns true if the sequence is already started up.
//
//  Parameters:
//    startup, output : true if the sequence is already started up.
bool halton_isstart ( );

// halton_scrambling_get -- 
// get the scrambling option.
//
//  Parameters:
//    Output, int scrambling: halton_scramblingZero or halton_scramblingRR2
int halton_scrambling_get (  );

__END_DECLS


#endif /* _LOWDISC_HALTON_D_H_ */

